// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LMSCore.Models
{
    public partial class Certificate
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int LevelId { get; set; }
        public string Url { get; set; }
        public DateTime DateCreated { get; set; }

        public virtual Level Level { get; set; }
    }
}