// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LMSCore.Models
{
    public partial class Course
    {
        public Course()
        {
            Levels = new HashSet<Level>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string VideoDemoUrl { get; set; }
        public string MainPhoto { get; set; }
        public short Price { get; set; }
        public short? Discount { get; set; }
        public string Image { get; set; }
        public bool? IsPaid { get; set; }
        public DateTime DateCreated { get; set; }

        public virtual ICollection<Level> Levels { get; set; }
    }
}