// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LMSCore.Models
{
    public partial class LessonItem
    {
        public int Id { get; set; }
        public int LessonItemTypeId { get; set; }
        public string VideoUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public short? OrderOfDisplay { get; set; }
        public DateTime DateCreated { get; set; }
    }
}